// lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart';

/// Hand-written Firebase configuration for the Android app.
///
/// Normally this file is auto-generated by running `flutterfire configure`
/// from a local terminal — since this project is built entirely from a
/// mobile device with no local CLI access, these values are instead taken
/// directly from android/app/google-services.json (already in the repo).
/// If you ever add an iOS build, this file will need an `ios` variant too.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfiHtnrJkgHugf6zlFMgToH8RGMdLOE4',
    appId: '1:687319123347:android:1209c4cab91a2a14bb5466',
    messagingSenderId: '687319123347',
    projectId: 'ludo-pro-max-d1986',
    databaseURL: 'https://ludo-pro-max-d1986-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-pro-max-d1986.firebasestorage.app',
  );
}
